#!/bin/bash

TIMESTAMP="$(date +"%y%m%d_%H%M%S")"
LOGS_DIR="$PWD/posdao-logs"

mkdir -p "$LOGS_DIR/$TIMESTAMP"

function collect_neth_log() {
    NETH_LOG="./data/node$1/nethermind.logs.txt"
    if [ -f "$NETH_LOG" ]; then
        echo "Collecting logs from neth node $1"
        cp "$NETH_LOG" "$LOGS_DIR/$TIMESTAMP/neth-node$1.logs.txt"
    fi
}

# Kill test nodes.
for i in $(seq 0 6); do
    collect_neth_log $i
done

if [ -L "$LOGS_DIR/latest" ]; then
    rm "$LOGS_DIR/latest"
fi
ln -s "$TIMESTAMP" "$LOGS_DIR/latest"

exit $1
