#!/bin/bash

TIMESTAMP=$(date +"%y%m%d_%H%M%S")
LOGS_DIR="$PWD/posdao-logs/$TIMESTAMP"

mkdir -p $LOGS_DIR

function collect_neth_log() {
    NETH_LOG="./data/node$1/nethermind.logs.txt"
    if [ -f "$NETH_LOG" ]; then
        echo "Collecting logs from neth node $1"
        cp "$NETH_LOG" "$LOGS_DIR/neth-node$1.logs.txt"
    else
        echo "No logs found for neth node $1"
    fi
}

function collect_lh_log() {
    echo "Collecting logs from lighthouse $1"
    docker-compose logs $1 > "$LOGS_DIR/lh-$1.logs.txt"
}

function kill_at_port {
	PID=`lsof -t -i:${1}`
	if [ "$PID" != "" ]; then
        echo Killing pid $PID at port $1
		kill -9 $PID
    else
        echo Nothing to kill at port $1
	fi
}

if [[ -d ./bc/launcher ]]; then
    cd ./bc/launcher
    collect_lh_log validator && docker-compose stop validator
    collect_lh_log node3 && docker-compose stop node3
    collect_lh_log node2 && docker-compose stop node2
    collect_lh_log node1 && docker-compose stop node1
    docker-compose down
    cd -
    # docker image rm sigp/lighthouse:v2.2.1-modern
    # docker image rm ghcr.io/gnosischain/deposit-script:latest
fi

# Kill test nodes.
for i in $(seq 0 6); do
    collect_neth_log $i
    kill_at_port 864$i
done
