version: '3.8'
services:
  node0:
    image: sigp/lighthouse
    hostname: node0
    command: |
      lighthouse beacon_node
      --testnet-dir /root/sbc/config
      --port 13000
      --execution-endpoint http://host.docker.internal:8740
      --execution-jwt /root/jwtsecret
      --datadir /home/.eth2/beaconchaindata
      --http-address 0.0.0.0
      --http-port 5050
      --http
      --disable-upnp
      --disable-discovery
      --debug-level debug
      --target-peers 3
      --libp2p-addresses /dns/host.docker.internal/tcp/13001/p2p/16Uiu2HAmN5seNB3AYkTo4qRC3oWsPTEGiR68w5suCcuqG3pSf4Ze,/dns/host.docker.internal/tcp/13002/p2p/16Uiu2HAmLCN7qTEBuknCa6R7thyTdUjALjYTpkSsrHhq3FKEL5q9,/dns/host.docker.internal/tcp/13003/p2p/16Uiu2HAm5xMT8ZbN2az5ozTXqmV1JxNh8CM9CkP9BHkPhGAJZMth
    ports:
      - '13000:13000'
      - '5050:5050'
    volumes:
      - ./jwtsecret:/root/jwtsecret
      - ./config:/root/sbc/config
      - ./node0_db:/home/.eth2/beaconchaindata
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
  node1:
    image: sigp/lighthouse
    hostname: node1
    command: |
      lighthouse beacon_node
      --testnet-dir /root/sbc/config
      --port 13001
      --execution-endpoint http://host.docker.internal:8741
      --execution-jwt /root/jwtsecret
      --datadir /home/.eth2/beaconchaindata
      --http-address 0.0.0.0
      --http-port 5051
      --http
      --disable-upnp
      --disable-discovery
      --debug-level debug
      --suggested-fee-recipient 0x0000000000000000000000000000000000000001
      --target-peers 3
      --libp2p-addresses /dns/host.docker.internal/tcp/13000/p2p/16Uiu2HAmJ7CvpzYR2QYWr3YTQBfeeYCqFVP3Ugm3XmSurG4WJzyC,/dns/host.docker.internal/tcp/13002/p2p/16Uiu2HAmLCN7qTEBuknCa6R7thyTdUjALjYTpkSsrHhq3FKEL5q9,/dns/host.docker.internal/tcp/13003/p2p/16Uiu2HAm5xMT8ZbN2az5ozTXqmV1JxNh8CM9CkP9BHkPhGAJZMth
    ports:
      - '13001:13001'
      - '5051:5051'
    volumes:
      - ./jwtsecret:/root/jwtsecret
      - ./config:/root/sbc/config
      - ./node1_db:/home/.eth2/beaconchaindata
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
  node2:
    image: sigp/lighthouse
    hostname: node2
    command: |
      lighthouse beacon_node
      --testnet-dir /root/sbc/config
      --port 13002
      --execution-endpoint http://host.docker.internal:8742
      --execution-jwt /root/jwtsecret
      --datadir /home/.eth2/beaconchaindata
      --http-address 0.0.0.0
      --http-port 5052
      --http
      --disable-upnp
      --disable-discovery
      --debug-level debug
      --suggested-fee-recipient 0x0000000000000000000000000000000000000002
      --target-peers 3
      --libp2p-addresses /dns/host.docker.internal/tcp/13000/p2p/16Uiu2HAmJ7CvpzYR2QYWr3YTQBfeeYCqFVP3Ugm3XmSurG4WJzyC,/dns/host.docker.internal/tcp/13001/p2p/16Uiu2HAmN5seNB3AYkTo4qRC3oWsPTEGiR68w5suCcuqG3pSf4Ze,/dns/host.docker.internal/tcp/13003/p2p/16Uiu2HAm5xMT8ZbN2az5ozTXqmV1JxNh8CM9CkP9BHkPhGAJZMth
    ports:
      - '13002:13002'
      - '5052:5052'
    volumes:
      - ./jwtsecret:/root/jwtsecret
      - ./config:/root/sbc/config
      - ./node2_db:/home/.eth2/beaconchaindata
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
  node3:
    image: sigp/lighthouse
    hostname: node3
    command: |
      lighthouse beacon_node
      --testnet-dir /root/sbc/config
      --port 13003
      --execution-endpoint http://host.docker.internal:8743
      --execution-jwt /root/jwtsecret
      --datadir /home/.eth2/beaconchaindata
      --http-address 0.0.0.0
      --http-port 5053
      --http
      --disable-upnp
      --disable-discovery
      --debug-level debug
      --suggested-fee-recipient 0x0000000000000000000000000000000000000003
      --target-peers 3
      --libp2p-addresses /dns/host.docker.internal/tcp/13000/p2p/16Uiu2HAmJ7CvpzYR2QYWr3YTQBfeeYCqFVP3Ugm3XmSurG4WJzyC,/dns/host.docker.internal/tcp/13001/p2p/16Uiu2HAmN5seNB3AYkTo4qRC3oWsPTEGiR68w5suCcuqG3pSf4Ze,/dns/host.docker.internal/tcp/13002/p2p/16Uiu2HAmLCN7qTEBuknCa6R7thyTdUjALjYTpkSsrHhq3FKEL5q9
    ports:
      - '13003:13003'
      - '5053:5053'
    volumes:
      - ./jwtsecret:/root/jwtsecret
      - ./config:/root/sbc/config
      - ./node3_db:/home/.eth2/beaconchaindata
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
  validator1:
    image: sigp/lighthouse
    hostname: validator
    depends_on:
      - node1
    command: |
      lighthouse validator_client
      --testnet-dir /root/sbc/config
      --validators-dir /var/lib/lighthouse/validators/
      --beacon-nodes http://node1:5051
      --graffiti-file /root/sbc/config/graffiti.yml
    volumes:
      - ./config:/root/sbc/config
      - ./validators/validator1:/var/lib/lighthouse/validators/
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"

  validator2:
    image: sigp/lighthouse
    hostname: validator
    depends_on:
      - node2
    command: |
      lighthouse validator_client
      --testnet-dir /root/sbc/config
      --validators-dir /var/lib/lighthouse/validators/
      --beacon-nodes http://node2:5052
      --graffiti-file /root/sbc/config/graffiti.yml
    volumes:
      - ./config:/root/sbc/config
      - ./validators/validator2:/var/lib/lighthouse/validators/
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"

  validator3:
    image: sigp/lighthouse
    hostname: validator
    depends_on:
      - node3
    command: |
      lighthouse validator_client
      --testnet-dir /root/sbc/config
      --validators-dir /var/lib/lighthouse/validators/
      --beacon-nodes http://node3:5053
      --graffiti-file /root/sbc/config/graffiti.yml
    volumes:
      - ./config:/root/sbc/config
      - ./validators/validator3:/var/lib/lighthouse/validators/
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
